<?php

namespace App\Services;

use App\Models\Conversation;
use App\Models\Message;
use App\Models\ServiceBooking;
use App\Models\SupportCase;
use App\Models\SupportCaseHistory;
use App\Models\AppointmentHistory;
use App\Models\User;
use App\Events\SupportCaseUpdated;
use App\Services\NotificationService;
use App\Services\SupportCaseIdService;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class BookingService
{
    protected NotificationService $notificationService;
    protected SupportCaseIdService $idService;

    public function __construct(
        NotificationService $notificationService,
        SupportCaseIdService $idService
    ) {
        $this->notificationService = $notificationService;
        $this->idService = $idService;
    }

    /**
     * Create a new service booking with conversation integration
     */
    /**
     * Create a standalone service booking (self-service from Services Page)
     * NO support case. NO conversation. Just a booking record + notification.
     */
    public function createBooking(array $data, $user, ?string $guestSessionId): array
    {
        return DB::transaction(function () use ($data, $user, $guestSessionId) {
            $description = $data['service_description'] ?? 'No description provided';
            $subject = $this->buildBookingSubject($data);

            // ─── Step 1: Create standalone service booking ───
            // ID is auto-generated by model boot() — do NOT pass 'id'
            $booking = ServiceBooking::create([
                'case_id' => null, // <-- NO case linked for self-service bookings
                'service_type' => $data['service_type'],
                'service_description' => $description,
                'estimated_price' => $data['estimated_price'] ?? null,
                'requested_date' => $data['requested_date'] ?? null,
                'preferred_time' => $data['preferred_time'] ?? null,
                'customer_name' => $data['customer_name'] ?? $user?->name ?? 'Guest',
                'customer_phone' => $data['customer_phone'] ?? null,
                'customer_email' => $data['customer_email'] ?? $user?->email ?? null,
                'guest_session_id' => $user ? null : $guestSessionId,
                'shop_location' => $data['shop_location'] ?? null,
                'status' => 'pending',
                'customer_notes' => $data['customer_notes'] ?? null,
                'metadata' => [
                    'booking_origin' => 'services_page',
                    'ip' => request()->ip(),
                    'user_agent' => request()->userAgent(),
                ],
            ]);

            // ─── Step 2: Notify customer (email/SMS) ───
            $this->notifyBookingCreatedStandalone($booking, $user);

            return [
                'service_booking' => $booking->fresh(['seller', 'assignedMechanic']),
                'support_case' => null,
                'conversation' => null,
                'system_message' => null,
            ];
        });
    }

    /**
     * Create a case-linked service booking (from chat modal / contact support)
     * This creates SupportCase + Conversation + links the booking.
     */
    public function createCaseLinkedBooking(array $data, $user, ?string $guestSessionId, SupportCase $supportCase, Conversation $conversation): ServiceBooking
    {
        $description = $data['service_description'] ?? 'No description provided';

        // ID is auto-generated by model boot() — do NOT pass 'id'
        $booking = ServiceBooking::create([
            'case_id' => $supportCase->case_id,
            'service_type' => $data['service_type'],
            'service_description' => $description,
            'estimated_price' => $data['estimated_price'] ?? null,
            'requested_date' => $data['requested_date'] ?? null,
            'preferred_time' => $data['preferred_time'] ?? null,
            'customer_name' => $data['customer_name'] ?? $user?->name ?? 'Guest',
            'customer_phone' => $data['customer_phone'] ?? null,
            'customer_email' => $data['customer_email'] ?? $user?->email ?? null,
            'guest_session_id' => $user ? null : $guestSessionId,
            'shop_location' => $data['shop_location'] ?? null,
            'status' => 'pending',
            'customer_notes' => $data['customer_notes'] ?? null,
        ]);

        // System message in conversation
        Message::create([
            'conversation_id' => $conversation->id,
            'case_id' => $supportCase->case_id,
            'sender_id' => null,
            'body' => "📅 Service Booking Added: {$this->buildBookingSubject($data)}",
            'type' => 'system',
            'metadata' => [
                'event_type' => 'service_booking_linked',
                'booking_id' => $booking->id,
                'case_id' => $supportCase->case_id,
            ],
        ]);

        return $booking;
    }

    /**
     * Confirm a booking (staff action)
     */
    public function confirmBooking(string $caseId, array $data, User $staff): array
    {
        return DB::transaction(function () use ($caseId, $data, $staff) {
            $case = SupportCase::where('case_id', $caseId)
                ->where('case_type', 'services_booking')
                ->firstOrFail();

            $booking = $case->serviceBooking;
            if (!$booking) {
                throw new \Exception('Service booking not found for this case.');
            }

            $oldStatus = $case->appointment_status;

            // Update case
            $case->appointment_status = 'confirmed';
            $case->staff_confirmed_at = now();
            $case->status = 'open';
            $case->assigned_to = $staff->id;
            $case->service_agent_id = $data['assigned_mechanic_id'] ?? $staff->id;
            $case->save();

            // Update booking
            $booking->status = 'confirmed';
            $booking->confirmed_date = $data['confirmed_date'];
            $booking->confirmed_time = $data['confirmed_time'] ?? null;
            $booking->assigned_mechanic_id = $data['assigned_mechanic_id'] ?? $staff->id;
            $booking->staff_notes = $data['staff_notes'] ?? null;
            $booking->final_price = $data['final_price'] ?? $booking->estimated_price;
            $booking->save();

            // Log appointment history
            AppointmentHistory::create([
                'case_id' => $case->case_id,
                'changed_by' => $staff->id,
                'from_status' => $oldStatus,
                'to_status' => 'confirmed',
                'from_date' => $booking->requested_date,
                'to_date' => $data['confirmed_date'],
                'from_time' => $booking->preferred_time,
                'to_time' => $data['confirmed_time'] ?? null,
                'to_seller_id' => $booking->seller_id,
                'to_mechanic_id' => $data['assigned_mechanic_id'] ?? $staff->id,
                'reason' => 'Booking confirmed by staff. Date: ' . $data['confirmed_date'],
                'metadata' => [
                    'confirmed_date' => $data['confirmed_date'],
                    'confirmed_time' => $data['confirmed_time'] ?? null,
                    'assigned_mechanic_id' => $data['assigned_mechanic_id'] ?? null,
                ],
            ]);

            // Create system message
            $systemMessage = Message::create([
                'conversation_id' => $case->conversation_id,
                'sender_id' => null,
                'body' => "✅ Appointment Confirmed\n\nDate: {$data['confirmed_date']}\n" .
                         (!empty($data['confirmed_time']) ? "Time: {$data['confirmed_time']}\n" : '') .
                         "Staff: {$staff->name}\n\nPlease arrive 10 minutes early.",
                'type' => 'system',
                'metadata' => [
                    'event_type' => 'booking_confirmed',
                    'case_id' => $case->case_id,
                    'confirmed_date' => $data['confirmed_date'],
                ],
                'case_id' => $case->case_id,
            ]);

            // Broadcast
            broadcast(new SupportCaseUpdated($case, 'booking_confirmed', $staff->id))->toOthers();

            // Notify customer
            $this->notifyBookingConfirmed($case, $booking);

            return [
                'support_case' => $case->fresh(),
                'service_booking' => $booking->fresh(),
                'system_message' => $systemMessage,
            ];
        });
    }

    /**
     * Reschedule a booking
     */
    public function rescheduleBooking(string $caseId, array $data, User $staff): array
    {
        return DB::transaction(function () use ($caseId, $data, $staff) {
            $case = SupportCase::where('case_id', $caseId)->firstOrFail();
            $booking = $case->serviceBooking;

            $oldDate = $booking->confirmed_date?->format('Y-m-d H:i') ?? 'Not set';

            $case->appointment_status = 'rescheduled';
            $case->appointment_at = $data['new_date'];
            $case->save();

            $oldBookingStatus = $booking->status;
            $oldConfirmedDate = $booking->confirmed_date;
            $booking->status = 'rescheduled';
            $booking->confirmed_date = $data['new_date'];
            $booking->staff_notes = ($booking->staff_notes ? $booking->staff_notes . "\n" : '') .
                                    "Rescheduled by {$staff->name} from {$oldDate} to {$data['new_date']}";
            $booking->save();

            // Log appointment history
            AppointmentHistory::create([
                'case_id' => $case->case_id,
                'changed_by' => $staff->id,
                'from_status' => $oldBookingStatus,
                'to_status' => 'rescheduled',
                'from_date' => $oldConfirmedDate,
                'to_date' => $data['new_date'],
                'reason' => "Rescheduled by {$staff->name} from {$oldDate} to {$data['new_date']}",
                'metadata' => [
                    'old_date' => $oldDate,
                    'new_date' => $data['new_date'],
                    'reschedule_reason' => $data['reason'] ?? null,
                ],
            ]);

            // System message
            $systemMessage = Message::create([
                'conversation_id' => $case->conversation_id,
                'sender_id' => null,
                'body' => "📅 Appointment Rescheduled\n\nNew Date: {$data['new_date']}\n" .
                         ($data['reason'] ? "Reason: {$data['reason']}" : ''),
                'type' => 'system',
                'metadata' => ['event_type' => 'booking_rescheduled'],
                'case_id' => $case->case_id,
            ]);

            broadcast(new SupportCaseUpdated($case, 'booking_rescheduled', $staff->id))->toOthers();

            return [
                'support_case' => $case->fresh(),
                'service_booking' => $booking->fresh(),
                'system_message' => $systemMessage,
            ];
        });
    }

    /**
     * Mark booking as completed
     */
    public function completeBooking(string $caseId, User $staff): array
    {
        return DB::transaction(function () use ($caseId, $staff) {
            $case = SupportCase::where('case_id', $caseId)->firstOrFail();
            $booking = $case->serviceBooking;

            $case->appointment_status = 'completed';
            $case->status = 'resolved';
            $case->resolved_at = now();
            $case->resolved_by = $staff->id;
            $case->save();

            $oldBookingStatus = $booking->status;
            $booking->status = 'completed';
            $booking->completed_date = now();
            $booking->save();

            // Log appointment history
            AppointmentHistory::create([
                'case_id' => $case->case_id,
                'changed_by' => $staff->id,
                'from_status' => $oldBookingStatus,
                'to_status' => 'completed',
                'to_date' => now(),
                'reason' => 'Service completed by staff',
                'metadata' => [
                    'completed_by' => $staff->id,
                    'completed_at' => now()->toDateTimeString(),
                ],
            ]);

            $systemMessage = Message::create([
                'conversation_id' => $case->conversation_id,
                'sender_id' => null,
                'body' => "✅ Service Completed\n\nThank you for choosing Oshocks! Your service has been completed.",
                'type' => 'system',
                'metadata' => ['event_type' => 'booking_completed'],
                'case_id' => $case->case_id,
            ]);

            broadcast(new SupportCaseUpdated($case, 'booking_completed', $staff->id))->toOthers();

            return [
                'support_case' => $case->fresh(),
                'service_booking' => $booking->fresh(),
                'system_message' => $systemMessage,
            ];
        });
    }

    /**
     * Cancel a booking
     */
    public function cancelBooking(string $caseId, string $reason, ?User $user = null): array
    {
        return DB::transaction(function () use ($caseId, $reason, $user) {
            $case = SupportCase::where('case_id', $caseId)->firstOrFail();
            $booking = $case->serviceBooking;

            $case->appointment_status = 'cancelled';
            $case->status = 'closed';
            $case->closed_at = now();
            $case->save();

            $oldBookingStatus = $booking->status;
            $booking->status = 'cancelled';
            $booking->cancelled_date = now();
            $booking->staff_notes = ($booking->staff_notes ? $booking->staff_notes . "\n" : '') .
                                    "Cancelled: {$reason}";
            $booking->save();

            // Log appointment history
            AppointmentHistory::create([
                'case_id' => $case->case_id,
                'changed_by' => $user?->id,
                'from_status' => $oldBookingStatus,
                'to_status' => 'cancelled',
                'reason' => $reason,
                'metadata' => [
                    'cancelled_by_role' => $user ? $user->role : 'guest',
                    'cancelled_by_id' => $user?->id,
                ],
            ]);

            $systemMessage = Message::create([
                'conversation_id' => $case->conversation_id,
                'sender_id' => null,
                'body' => "❌ Appointment Cancelled\n\nReason: {$reason}",
                'type' => 'system',
                'metadata' => ['event_type' => 'booking_cancelled'],
                'case_id' => $case->case_id,
            ]);

            broadcast(new SupportCaseUpdated($case, 'booking_cancelled', $user?->id))->toOthers();

            return [
                'support_case' => $case->fresh(),
                'service_booking' => $booking->fresh(),
                'system_message' => $systemMessage,
            ];
        });
    }

    /**
     * Find or create a single conversation per user for appointments
     */
    protected function getOrCreateUserConversation($user, ?string $guestSessionId): Conversation
    {
        $query = Conversation::whereIn('type', ['support', 'order_support']);

        if ($user) {
            $query->where(function ($q) use ($user) {
                $q->where('created_by', $user->id)
                  ->orWhereHas('participants', function ($pq) use ($user) {
                      $pq->where('user_id', $user->id);
                  });
            });
        } elseif ($guestSessionId) {
            $query->where('guest_session_id', $guestSessionId);
        }

        // Look for existing conversation without an order_id (general support)
        $existing = $query->whereNull('order_id')->first();

        if ($existing) {
            return $existing;
        }

        // Create new conversation
        $supportUser = \App\Models\User::whereIn('role', ['admin', 'super_admin'])->first();

        $conversation = Conversation::create([
            'created_by' => $user?->id,
            'guest_session_id' => $user ? null : $guestSessionId,
            'type' => 'support',
            'title' => $user ? "Appointments - {$user->name}" : 'Appointments - Guest',
            'status' => 'open',
            'priority' => 'medium',
        ]);

        if ($user) {
            $conversation->participants()->attach($user->id, ['joined_at' => now()]);
        }

        if ($supportUser && $supportUser->id !== $user?->id) {
            $conversation->participants()->attach($supportUser->id, [
                'joined_at' => now(),
                'is_admin' => true,
            ]);
        }

        return $conversation;
    }

    /**
     * Build the booking subject line from form data
     * Format: "{ServiceType} service on {Date} at {Time} at {Shop}"
     */
    protected function buildBookingSubject(array $data): string
    {
        $serviceType = str_replace('_', ' ', $data['service_type'] ?? 'Service');
        $date = $data['requested_date'] ?? 'TBD';
        $time = $data['preferred_time'] ?? 'TBD';
        $shop = $data['shop_location'] ?? 'TBD';

        // Format date nicely if it's a valid date
        if ($date !== 'TBD') {
            try {
                $date = \Carbon\Carbon::parse($date)->format('M j, Y');
            } catch (\Exception $e) {
                // Keep as-is if parsing fails
            }
        }

        return "{$serviceType} service on {$date} at {$time} at {$shop}";
    }

    /**
     * Create system message for new booking
     */
    protected function createBookingSystemMessage(int $conversationId, SupportCase $case, ServiceBooking $booking): Message
    {
        $details = $case->service_details ?? [];
        $body = "🔧 New Service Booking Created\n\n" .
                "Case: {$case->case_id}\n" .
                "Service: {$booking->service_type}\n" .
                "Requested Date: " . ($booking->requested_date?->format('M j, Y g:i A') ?? 'Not specified') . "\n" .
                "Status: Pending Confirmation\n\n" .
                "Our team will review and confirm your appointment shortly.";

        return Message::create([
            'conversation_id' => $conversationId,
            'sender_id' => null,
            'body' => $body,
            'type' => 'system',
            'metadata' => [
                'event_type' => 'booking_created',
                'case_id' => $case->case_id,
                'service_type' => $booking->service_type,
            ],
            'case_id' => $case->case_id,
        ]);
    }

    /**
     * Notify customer of booking creation
     */
    protected function notifyBookingCreated(SupportCase $case, ServiceBooking $booking, ?User $user): void
    {
        try {
            NotificationService::sendGuestNotification(
                $user,
                $booking->customer_email,
                $booking->customer_phone,
                'booking_created',
                [
                    'case_id' => $case->case_id,
                    'service_type' => $booking->service_type,
                    'requested_date' => $booking->requested_date?->format('M j, Y'),
                    'customer_name' => $booking->customer_name,
                ]
            );
        } catch (\Exception $e) {
            Log::error('Failed to send booking creation notification', [
                'case_id' => $case->case_id,
                'error' => $e->getMessage(),
            ]);
        }
    }

    /**
     * Notify customer of booking confirmation
     */
    protected function notifyBookingConfirmed(SupportCase $case, ServiceBooking $booking): void
    {
        try {
            $user = $case->user_id ? User::find($case->user_id) : null;

            NotificationService::sendGuestNotification(
                $user,
                $booking->customer_email,
                $booking->customer_phone,
                'booking_confirmed',
                [
                    'case_id' => $case->case_id,
                    'service_type' => $booking->service_type,
                    'confirmed_date' => $booking->confirmed_date?->format('M j, Y g:i A'),
                    'shop_location' => $booking->shop_location,
                    'customer_name' => $booking->customer_name,
                ]
            );
        } catch (\Exception $e) {
            Log::error('Failed to send booking confirmation notification', [
                'case_id' => $case->case_id,
                'error' => $e->getMessage(),
            ]);
        }
    }

    /**
     * Notify customer of standalone booking creation (no case)
     */
    protected function notifyBookingCreatedStandalone(ServiceBooking $booking, ?User $user): void
    {
        try {
            // Use NotificationService class directly (static or injected)
            \App\Services\NotificationService::sendGuestNotification(
                $user,
                $booking->customer_email,
                $booking->customer_phone,
                'booking_created_standalone',
                [
                    'booking_id' => $booking->id,
                    'service_type' => $booking->service_type,
                    'requested_date' => $booking->requested_date?->format('M j, Y'),
                    'shop_location' => $booking->shop_location,
                    'customer_name' => $booking->customer_name,
                ]
            );
        } catch (\Exception $e) {
            Log::error('Failed to send standalone booking notification', [
                'booking_id' => $booking->id,
                'error' => $e->getMessage(),
            ]);
        }
    }
}
